# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a39b2428fee6b52ef60a7c1cfe186febf5c10b9c54bda7932982231a41a81f95459777ecbc2308a7363b7966ae7eab7bee4239b7d16d205466e80e5bc58e991d

test:
  secret_key_base: 63935422b544c0bb224afa38e4c6daac8115245dc3a2a57d69f28bc4f84cf7dfa68e8a0a9be1352d50d13ea56efc0af99c9a14bcbc515a25c6ce472f83002ecb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
